blank_issues_enabled: false
contact_links:
  - name: ❓️ Question
    url: https://github.com/mrjones2014/smart-splits.nvim/discussions
    about: Please create a GitHub Discussion for general questions
