name: Run All Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-lua:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup 'lua'
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"
    - name: Run Stylua
      uses: JohnnyMorganz/stylua-action@v1.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check lua/
        version: 0.15.2
    - name: Run Luacheck
      uses: lunarmodules/luacheck@v1
      with:
        args: lua/
