name: CI
on:
  push:
      branches:
        - "main"
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Stylua check
        uses: JohnnyMorganz/stylua-action@v2
        with:
          # token is needed because the action allegedly downloads binary from github releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .
          version: latest
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          CHECK_ONLY_DEFAULT_BRANCH: true
  release:
    name: release

    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - stylua
      - generateTOC
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: mason-null-ls.nvim
      - uses: actions/checkout@v3
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable


