name: generate

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Generate
        shell: bash
        run: make generate

      - name: Run tests
        shell: bash
        run: make test

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: |
            Update SchemaStore catalog

            This commit was performed automatically by GitHub Actions.
