return {
  "               ...''''...               ",
  "          .'''..        .''''           ",
  "       .,,.                  .c'        ",
  "      ;'                      cdd,      ",
  "    ';     .....             ;.lddo.    ",
  "   ;' .;lddlcccdddc,.       .d. dodd.   ",
  "  ,,'odo,.  .:dddolodl.   ,o:d.. .ldd.  ",
  "  o:dd'    ldl'.      ..   .cd. 'dldd:  ",
  " .ddd.    od'               .c.,oodddd  ",
  " .ddl    .d:                  cddddddd  ",
  "  dd;     dc                  cddddddc  ",
  "  :d:     .o;                 cdddddd.  ",
  "   ld       .:,.              cddddd,   ",
  "    cc         .,,,,'.......  cdddd'    ",
  "     .:.                      cddc.     ",
  "       ';.                    l:.       ",
  "         .','.           ..',.          ",
  "             ..''''''''''.              ",
}
